Controllers/GlobalsController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using BasicCore7.Data;
using BasicCore7.Models;
using Microsoft.AspNetCore.Authorization;
using BasicCore7.Services;

namespace BasicCore7.Controllers
{
    [Authorize (Roles = "SystemAdministrator")]
    public class GlobalsController : Controller
    {
        private readonly BasicCore7Context _context;

        public GlobalsController(BasicCore7Context context)
        {
            _context = context;
        }

        // GET: Globals
        public async Task<IActionResult> Index()
        {
              return _context.Globals != null ? 
                          View(await _context.Globals.ToListAsync()) :
                          Problem("Entity set 'BasicCore7DbContext.Globals'  is null.");
        }

        // GET: Globals/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Globals == null)
            {
                return NotFound();
            }

            var @global = await _context.Globals
                .FirstOrDefaultAsync(m => m.Id == id);
            if (@global == null)
            {
                return NotFound();
            }

            return View(@global);
        }

        // GET: Globals/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Globals == null)
            {
                return NotFound();
            }

            var @global = await _context.Globals.FindAsync(id);
            if (@global == null)
            {
                return NotFound();
            }
            return View(@global);
        }

        // POST: Globals/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Value,Description")] Global @global)
        {
            if (id != @global.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(@global);
                    await _context.SaveChangesAsync();
                    Globals.ApplyGlobals(_context);
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!GlobalExists(@global.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(@global);
        }


        private bool GlobalExists(string id)
        {
          return (_context.Globals?.Any(e => e.Id == id)).GetValueOrDefault();
        }
    }
}

Controllers/LanguagesController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Localization;
using BasicCore7.Data;
using BasicCore7.Models;
using BasicCore7.Controllers;

namespace BasicCore7.Controllers
{
    public class LanguagesController : CultController
    {

        public LanguagesController(BasicCore7Context context, 
            IHttpContextAccessor httpContextAccessor,
            ILogger<CultController> logger)
            : base(context, httpContextAccessor, logger)
        {
        }

        // GET: Languages
        public async Task<IActionResult> Index()
        {
              return View(await _context.Language.ToListAsync());
        }

        // GET: Languages/Details/5

        // GET: Languages/Create
        public IActionResult Create()
        {
            Language model = new Language { Cultures = "" };

            return View(model);
        }

        // POST: Languages/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Cultures,IsShown")] Language language)
        {
            if (language.Cultures == null)
                language.Cultures = "";
            if (ModelState.IsValid)
            {
                _context.Add(language);
                await _context.SaveChangesAsync();
                Language.Initialize(_context);
                // zorg dat het systeem beschikt over een nieuwe lijst van gebruikte cultures
                try
                {
                    var localizationOptions = new RequestLocalizationOptions()
                        .AddSupportedCultures(Language.SupportedCultures)
                        .AddSupportedUICultures(Language.SupportedCultures)
                        .SetDefaultCulture("nl-BE");
                }
                catch
                {
                    _context.Remove(language);
                    await _context.SaveChangesAsync();
                    ViewData["ErrorMessage"] = "De code moet 2 kleine letters zijn, de culturelijst telkens 2 hoofdletters, gescheiden door een ';'";
                    return View(language);
                }
                return RedirectToAction(nameof(Index));
            }

            return View(language);
        }

        // GET: Languages/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Language == null)
            {
                return NotFound();
            }

            var language = await _context.Language.FindAsync(id);
            if (language.Cultures == null)
                language.Cultures = "";
            return View(language);
        }

        // POST: Languages/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("Id,Name,Cultures,IsShown")] Language language)
        {
            if (language.Cultures == null)
                language.Cultures = "";
            Language oldLanguage = _context.Language.FirstOrDefault(l => l.Id == language.Id);

            if (ModelState.IsValid)
            {
                 _context.Update(language);
                 await _context.SaveChangesAsync();

                Language.Initialize(_context);
                // zorg dat het systeem beschikt over een nieuwe lijst van gebruikte cultures
                try
                {
                    var localizationOptions = new RequestLocalizationOptions()
                        .AddSupportedCultures(Language.SupportedCultures)
                        .AddSupportedUICultures(Language.SupportedCultures)
                        .SetDefaultCulture("nl-BE");
                }
                catch
                {
                    
                    _context.Update(oldLanguage);
                    await _context.SaveChangesAsync();
                    ViewData["ErrorMessage"] = "De code moet 2 kleine letters zijn, de culturelijst telkens 2 hoofdletters, gescheiden door een ';'";
                    return View(language);
                }

                return RedirectToAction(nameof(Index));
            }
            return View(language);
        }

        public IActionResult ChangeLanguage(string id, string returnUrl)
        {
            string culture = Thread.CurrentThread.CurrentCulture.ToString();
            try
            {
                culture = id + culture.Substring(2, 3);
            }
            catch
            {
                culture = id + "-BE";
            }

            Response.Cookies.Append(
                CookieRequestCultureProvider.DefaultCookieName,
                CookieRequestCultureProvider.MakeCookieValue(new RequestCulture(culture)),
                new CookieOptions { Expires = DateTimeOffset.UtcNow.AddYears(1) });

            if (User.Identity.IsAuthenticated)
            {
                Language language = _context.Language.FirstOrDefault(l => l.Id == id);
                _user.Language = language;
                BasicCore7User user = _context.Users.FirstOrDefault(u => u.Id == _user.Id);
                user.Language = language;
                user.LanguageId = id;
                _context.SaveChanges();
            }


            return LocalRedirect(returnUrl);
        }
    }
}

Controllers/UsersController.cs
using BasicCore7.Data;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Authorization;
using BasicCore7.Models;
using Microsoft.AspNetCore.Mvc.Rendering;
using BasicCore7.Controllers;

namespace GroupSpace2022.Controllers
{
    [Authorize (Roles = "UserAdministrator")]
    public class UsersController : CultController
    {

        public UsersController(BasicCore7Context context, IHttpContextAccessor httpContextAccessor, ILogger<CultController> logger)
            : base(context, httpContextAccessor, logger)
        {
        }

        public IActionResult Index(string userName, string firstName, string lastName, string email, int? pageNumber)
        {
            List<UserViewModel> vmUsers = new List<UserViewModel>();
            List<BasicCore7User> users = _context.Users
                                                .Where( u => u.UserName != "Dummy"
                                                        && (u.UserName.Contains(userName) || string.IsNullOrEmpty(userName))
                                                        && (u.FirstName.Contains(firstName) || string.IsNullOrEmpty(firstName))
                                                        && (u.LastName.Contains(lastName) || string.IsNullOrEmpty(lastName))
                                                        && (u.Email.Contains(email) || string.IsNullOrEmpty(email)))
                                                .ToList();
            foreach (BasicCore7User user in users)
            {
                vmUsers.Add(new UserViewModel
                {
                    Deleted = user.Blocked < DateTime.Now,
                    Email = user.Email,
                    FirstName = user.FirstName,
                    LastName = user.LastName,
                    UserName = user.UserName,
                    Roles = (from userRole in _context.UserRoles
                             where userRole.UserId == user.Id
                             orderby userRole.RoleId
                             select userRole.RoleId).ToList()
                });
            }
            ViewData["userName"] = userName;
            ViewData["firstName"] = firstName;
            ViewData["lastName"] = lastName;
            ViewData["email"] = email;
            if (pageNumber == null) pageNumber = 1;
            PageList<UserViewModel> model = new PageList<UserViewModel>(vmUsers, vmUsers.Count, 1, 10);
            return View(model);
        }

        public IActionResult Undelete(string userName)
        {
            BasicCore7User user = _context.Users.FirstOrDefault(u => u.UserName == userName);
            user.Blocked = DateTime.MaxValue;
            _context.Update(user);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

        public IActionResult Delete(string userName)
        {
            BasicCore7User user = _context.Users.FirstOrDefault(u => u.UserName == userName);
            user.Blocked = DateTime.Now;
            _context.Update(user);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }


        public IActionResult Roles(string userName)
        {

            BasicCore7User user = _context.Users.FirstOrDefault(u => u.UserName == userName);
            RoleViewModel rvm = new RoleViewModel()
            {
                UserName = userName,
                Roles = (from userRole in _context.UserRoles
                        where userRole.UserId == user.Id
                        orderby userRole.RoleId
                        select userRole.RoleId).ToList()
            };

            ViewData["RoleIds"] = new MultiSelectList(_context.Roles.OrderBy(c => c.Name), "Id", "Name",rvm.Roles);
            return View(rvm);
        }

        [HttpPost]
        public IActionResult Roles([Bind("UserName,Roles")] RoleViewModel _model)
        {
            BasicCore7User user = _context.Users.FirstOrDefault(u => u.UserName == _model.UserName);
            List<IdentityUserRole<string>> userRoles = _context.UserRoles.Where(ur => ur.UserId == user.Id).ToList();
            foreach (IdentityUserRole<string> ur in userRoles)
            {
                _context.Remove(ur);
            }
            if (_model.Roles != null)
                foreach (string roleId in _model.Roles)
                    _context.UserRoles.Add(new IdentityUserRole<string>() { RoleId = roleId, UserId = user.Id });
            _context.SaveChanges();
            return RedirectToAction("Index");
        }

    }
}

Views/Shared/_LanguagePartial.cshtml
@using Microsoft.AspNetCore.Localization;
@using Microsoft.AspNetCore.Mvc.Localization;

@{
    string languageId = "nl";
    string cookieCulture = Context.Request.Cookies[CookieRequestCultureProvider.DefaultCookieName];
    if (cookieCulture != null)
    {
        languageId = cookieCulture.Substring(2, 2);
    }
    string languageName = Language.LanguagesDictionary[languageId].Name;

    //ophalen huidige pagina
    var thisPage = string.IsNullOrEmpty(Context.Request.Path) ? "~/index.html" : $"~{Context.Request.Path.Value}";
}

<ul class="navbar-nav">
    <li class="nav-item dropdown">
        <a class="nav-link text-dark dropdown" data-bs-toggle="dropdown">@languageName</a>
        <ul class="dropdown-menu">
            @foreach (Language l in Language.Languages)
                if (l.Id != languageId && l.IsShown)
                {
                    <li class="nav-item">
                        <a class="nav-link text-dark" 
                            asp-area="" 
                            asp-controller="Languages"
                            asp-action="ChangeLanguage"
                            asp-route-id="@l.Id"
                            asp-route-returnUrl=@thisPage>
                            @l.Name
                        </a>
                    </li>
                }
        </ul>
    </li>
</ul>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
@using Microsoft.AspNetCore.Mvc.Localization
@inject IViewLocalizer Localizer

<html>

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - BasicCore7</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/BasicCore7.styles.css" asp-append-version="true" />
</head>

@{
    // Haal de huidige ApplicationUser op, m.i.v. de groepen
    // Gebruik hiervoor de Middleware toegevoegde Globals klasse
    BasicCore7.Data.BasicCore7User _user = BasicCore7.Services.Globals.GetUser(User.Identity.Name);
}

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">@Localizer["Home"]</a>
                        </li>
                        @if (User.IsInRole("SystemAdministrator") || User.IsInRole("UserAdministrator"))
                        {
                            <li class="nav-item dropdown">
                                <a href="#" class="nav-link dropdown-toggle text-dark" data-bs-toggle="dropdown">@Localizer["System"]</a>
                                <ul class="dropdown-menu">
                                    @if (User.IsInRole("SystemAdministrator"))
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-controller="Globals" asp-action="Index">@Localizer["Parameters"]</a>
                                        </li>
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-controller="Languages" asp-action="Index">@Localizer["Languages"]</a>
                                        </li>
                                    }
                                    @if (User.IsInRole("UserAdministrator"))
                                    {
                                        <li class="nav-item">
                                            <a class="nav-link text-dark" asp-controller="Users" asp-action="Index">@Localizer["Users"]</a>
                                        </li>
                                    }
                                </ul>
                            </li>
                        }
                    </ul>
                    <partial name="_LoginPartial" />
                    @if (!User.Identity.IsAuthenticated)
                    {
                        <partial name="_LanguagePartial" />
                    }
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - BasicCore7 - <a asp-area="" asp-controller="Home" asp-action="Privacy">@Localizer["Privacy"]</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>